<?php

use App\Distrito;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class DistritoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Distrito::insert([
            ['nombre' => 'Carmen', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Merced', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Hospital', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Catedral', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Zapote', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Francisco', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Uruca', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mata Redonda', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pavas', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Hatillo', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Sebastían', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Escazú', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Desamparados', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Miguel', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan de Dios', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael Arriba', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Frailes', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Patarrá', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Cristobal', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rosario', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Damas', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael Abajo', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Gravilias', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santiago', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mercedes Sur', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Barbacoas', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Grifo Alto', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Candelaria', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Desamparaditos', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Chires', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Marcos', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Lorenzo', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Carlos', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Aserrí', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tarbaca', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Vuelta de Jorco', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Gabriel', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Legua', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Monterrey', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Salitrillos', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cólon', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guayabo', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tabarcia', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Piedras Negras', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Picagres', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guadalupe', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Francisco', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Calle Blancos', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mata de Plátano', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ipis', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rancho Redondo', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Purral', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Ana', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Salitral', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pozos', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Uruca', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Piedades', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Brasil', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Alajuelita', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Josecito', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Concepción', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Felipe', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Isidro', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Dulce Nombre/Jesús', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Patalillo', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cascajal', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Ignacio', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guatil', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Palmichal', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cangrejal', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sabanillas', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cinco Esquinas', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Anselmo Llorente', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'León XIII', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Colima', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Vicente', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Jerónimo', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Trinidad', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pedro', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sabanilla', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mercedes/Betánia', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pablo', 'id_canton' => '16', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pedro', 'id_canton' => '16', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan de Mata', 'id_canton' => '16', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Luis', 'id_canton' => '16', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa María', 'id_canton' => '17', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jardín', 'id_canton' => '17', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Copey', 'id_canton' => '17', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Curridabat', 'id_canton' => '18', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Granadilla', 'id_canton' => '18', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sánchez', 'id_canton' => '18', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tirrases', 'id_canton' => '18', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Isidro del General', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'General', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Daniel Flores', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rivas', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pedro', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Platanares', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pejibaye', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cajón', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Barú', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rio Nuevo', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Páramo', 'id_canton' => '19', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pablo', 'id_canton' => '20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Andres', 'id_canton' => '20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Llano Bonito', 'id_canton' => '20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Isidro', 'id_canton' => '20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Cruz', 'id_canton' => '20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '20', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Alajuela', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Carrizal', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Antonio', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Guacima', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sabanilla', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rio Segundo', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Desamparados', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Turrucares', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tambor', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'La Garita', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sarapiqui', 'id_canton' => '21', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Ramón', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Santiago', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Juan', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Piedades norte', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Piedades sur', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Angeles', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Alfaro', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Volio', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Concepción', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zapotal', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Peñas Blancas', 'id_canton' => '22', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Grecia', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Roque', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tacares', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rio Cuarto', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Puente de Piedra', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Bolivar', 'id_canton' => '23', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Mateo', 'id_canton' => '24', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Desmonte', 'id_canton' => '24', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Jesús María', 'id_canton' => '24', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Atenas', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Jesús', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Mercedes', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Concepción', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Santa Eulalia', 'id_canton' => '25', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Naranjo', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Miguel', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Cirrí Sur', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Jerónimo', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Juan', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rosario', 'id_canton' => '26', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Palmares', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zaragoza', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Buenos Aires', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Santiago', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Candelaria', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Esquipulas', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Granja', 'id_canton' => '27', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Pedro', 'id_canton' => '28', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Juan', 'id_canton' => '28', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '28', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Carrillos', 'id_canton' => '28', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sabana Redonda', 'id_canton' => '28', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Orotina', 'id_canton' => '29', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Mastate', 'id_canton' => '29', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Hacienda Vieja', 'id_canton' => '29', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Coyolar', 'id_canton' => '29', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Ceiba', 'id_canton' => '29', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Quesada', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Florencia', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Buenavista', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Aguas Zarcas', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Venecia', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Pital', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Fortuna', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tigra', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Palmera', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Venado', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Cutris', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Monterrey', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Pocosol', 'id_canton' => '30', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zarcero', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Laguna', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tapezco', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Guadalupe', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Palmira', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zapote', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Brisas', 'id_canton' => '31', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sarchí Norte', 'id_canton' => '32', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sarchí Sur', 'id_canton' => '32', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Toro Amarillo', 'id_canton' => '32', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Pedro', 'id_canton' => '32', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rodríguez', 'id_canton' => '32', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Upala', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Aguas Claras', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José/Pizote', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Bijagua', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Delicias', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Dos Ríos', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Yolillal', 'id_canton' => '33', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Los Chiles', 'id_canton' => '34', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Caño Negro', 'id_canton' => '34', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'El Amparo', 'id_canton' => '34', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Jorge', 'id_canton' => '34', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '35', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Buenavista', 'id_canton' => '35', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Cote', 'id_canton' => '35', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Oriental', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Occidental', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Carmen', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Nicolas', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Aguacaliente/S.Francisco', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guadalupe', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Corralillo', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tierra Blanca', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Dulce Nombre', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Llano Grande', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Quebradilla', 'id_canton' => '36', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Paraíso', 'id_canton' => '37', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santiago', 'id_canton' => '37', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Orosí', 'id_canton' => '37', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cachí', 'id_canton' => '37', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tres Riós', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Diego', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Concepción', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Dulce Nombre', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Ramón', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Río Azul', 'id_canton' => '38', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Juan Viñas', 'id_canton' => '39', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tucurrique', 'id_canton' => '39', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pejiballe', 'id_canton' => '39', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Turrialba', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Suiza', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Peralta', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Cruz', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Teresita', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pavones', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tuis', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tayutic', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Rosa', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tres Equis', 'id_canton' => '40', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pacayas', 'id_canton' => '41', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cervantes', 'id_canton' => '41', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Capellades', 'id_canton' => '41', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '42', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cot', 'id_canton' => '42', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Potrero Cerrado', 'id_canton' => '42', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cipreses', 'id_canton' => '42', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Rosa', 'id_canton' => '42', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tejar', 'id_canton' => '43', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Isidro', 'id_canton' => '43', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tobosi', 'id_canton' => '43', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Patio de Agua', 'id_canton' => '43', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Heredia', 'id_canton' => '44', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mercedes', 'id_canton' => '44', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Francisco', 'id_canton' => '44', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Ulloa', 'id_canton' => '44', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Vara Blanca', 'id_canton' => '44', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Barva', 'id_canton' => '45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pedro', 'id_canton' => '45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pablo', 'id_canton' => '45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Roque', 'id_canton' => '45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Lucía', 'id_canton' => '45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San José de la Montaña', 'id_canton' => '45', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santo Domingo', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Vicente', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Miguel', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Paracito', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santo Tomas', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Rosa', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tures', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pará', 'id_canton' => '46', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Bárbara', 'id_canton' => '47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pedro', 'id_canton' => '47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan', 'id_canton' => '47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jesús', 'id_canton' => '47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santo Domingo del Roble', 'id_canton' => '47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Purabá', 'id_canton' => '47', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '48', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Josecito', 'id_canton' => '48', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santiago', 'id_canton' => '48', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Angeles', 'id_canton' => '48', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Concepción', 'id_canton' => '48', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Isidro', 'id_canton' => '49', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San José', 'id_canton' => '49', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Concepción', 'id_canton' => '49', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '50', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Rivera', 'id_canton' => '50', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Asunción', 'id_canton' => '50', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Joaquín', 'id_canton' => '51', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Barrantes', 'id_canton' => '51', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Llorente', 'id_canton' => '51', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pablo', 'id_canton' => '52', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Puerto Viejo', 'id_canton' => '53', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Virgen', 'id_canton' => '53', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Horquetas', 'id_canton' => '53', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Llanuras del Gaspar', 'id_canton' => '53', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cureña', 'id_canton' => '53', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Liberia', 'id_canton' => '54', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cañas Dulces', 'id_canton' => '54', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mayorga', 'id_canton' => '54', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Nacascolo', 'id_canton' => '54', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Curubandé', 'id_canton' => '54', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Nicoya', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mansión', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Antonio', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Quebrada Honda', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sámara', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Nosara', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Belén de Nosarita', 'id_canton' => '55', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Cruz', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bolsón', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Veintisiete de abril', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tempate', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cartagena', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cuajiniquil', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Diría', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cabo Velas', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tamarindo', 'id_canton' => '56', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bagaces', 'id_canton' => '57', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Fortuna', 'id_canton' => '57', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mogote', 'id_canton' => '57', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Río Naranjo', 'id_canton' => '57', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Filadelfia', 'id_canton' => '58', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Palmira', 'id_canton' => '58', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sardinal', 'id_canton' => '58', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Belén', 'id_canton' => '58', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cañas', 'id_canton' => '59', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Palmira', 'id_canton' => '59', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Miguel', 'id_canton' => '59', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bebedero', 'id_canton' => '59', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Porozal', 'id_canton' => '59', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Juntas', 'id_canton' => '60', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sierra', 'id_canton' => '60', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan', 'id_canton' => '60', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Colorado', 'id_canton' => '60', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tilarán', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Quebrada Grande', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tronadora', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Rosa', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Líbano', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tierras Morenas', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Arenal', 'id_canton' => '61', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Carmona', 'id_canton' => '62', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Rita', 'id_canton' => '62', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Zapotal', 'id_canton' => '62', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Pablo', 'id_canton' => '62', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Porvenir', 'id_canton' => '62', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bejuco', 'id_canton' => '62', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Cruz', 'id_canton' => '63', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Cecilia', 'id_canton' => '63', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Garita', 'id_canton' => '63', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Santa Elena', 'id_canton' => '63', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Hojancha', 'id_canton' => '64', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Monte Romo', 'id_canton' => '64', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Puerto Carrillo', 'id_canton' => '64', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Huacas', 'id_canton' => '64', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Puntarenas', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pitahaya', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Chomes', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Lepanto', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Paquera', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Manzanillo', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guacimal', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Barranca', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Monteverde', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cóbano', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Chacarita', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Chira', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Acapulco', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'El Roble', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Arancibia', 'id_canton' => '65', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Espiritu Santo', 'id_canton' => '66', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Juan Grande', 'id_canton' => '66', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Macacona', 'id_canton' => '66', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Rafael', 'id_canton' => '66', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Jerónimo', 'id_canton' => '66', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Buenos Aires', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Volcán', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Potrero Grande', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Boruca', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pilas', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Colinas', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Changuena', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Biolley', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Brunca', 'id_canton' => '67', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Miramar', 'id_canton' => '68', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Unión', 'id_canton' => '68', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Isidro', 'id_canton' => '68', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Puerto Cortés', 'id_canton' => '69', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Palmar', 'id_canton' => '69', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sierpe', 'id_canton' => '69', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bahía Ballena', 'id_canton' => '69', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Piedras Blancas', 'id_canton' => '69', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Quepos', 'id_canton' => '70', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Savegre', 'id_canton' => '70', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Naranjito', 'id_canton' => '70', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Golfito', 'id_canton' => '71', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Puerto Jiménez', 'id_canton' => '71', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guaycará', 'id_canton' => '71', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pavón', 'id_canton' => '71', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'San Vito', 'id_canton' => '72', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sabalito', 'id_canton' => '72', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Agua Buena', 'id_canton' => '72', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Limoncito', 'id_canton' => '72', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pittier', 'id_canton' => '72', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Parrita', 'id_canton' => '73', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Corredor', 'id_canton' => '74', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'La Cuesta', 'id_canton' => '74', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Canoas', 'id_canton' => '74', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Laurel', 'id_canton' => '74', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jacó', 'id_canton' => '75', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Tarcoles', 'id_canton' => '75', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Limón', 'id_canton' => '76', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Valle La Estrella', 'id_canton' => '76', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Río Blanco', 'id_canton' => '76', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Matama', 'id_canton' => '76', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guápiles', 'id_canton' => '77', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Jiménez', 'id_canton' => '77', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Rita', 'id_canton' => '77', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Roxana', 'id_canton' => '77', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cariari', 'id_canton' => '77', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Colorado', 'id_canton' => '77', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Siquirres', 'id_canton' => '78', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pacuarito', 'id_canton' => '78', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Florida', 'id_canton' => '78', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Germania', 'id_canton' => '78', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cairo', 'id_canton' => '78', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Alegría', 'id_canton' => '78', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Bratsi', 'id_canton' => '79', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Sixaola', 'id_canton' => '79', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Cahuita', 'id_canton' => '79', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Matina', 'id_canton' => '80', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Batán', 'id_canton' => '80', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Carrandi', 'id_canton' => '80', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Guacimo', 'id_canton' => '81', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Mercedes', 'id_canton' => '81', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Pocora', 'id_canton' => '81', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Río Jiménez', 'id_canton' => '81', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['nombre' => 'Duacari', 'id_canton' => '81', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
    		]);
    }














































































}
