<?php

use App\Distrito;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class DistritoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Distrito::insert([
    		['nombre' => 'Alajuela', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Carrizal', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Antonio', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Guacima', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sabanilla', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rio Segundo', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Desamparados', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Turrucares', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tambor', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'La Garita', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sarapiqui', 'id_canton' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Ramón', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Santiago', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Juan', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Piedades norte', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Piedades sur', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Angeles', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Alfaro', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Volio', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Concepción', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zapotal', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Peñas Blancas', 'id_canton' => '2', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Grecia', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Roque', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tacares', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rio Cuarto', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Puente de Piedra', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Bolivar', 'id_canton' => '3', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Mateo', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Desmonte', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Jesús María', 'id_canton' => '4', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Atenas', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Jesús', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Mercedes', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Isidro', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Concepción', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Santa Eulalia', 'id_canton' => '5', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Naranjo', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Miguel', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Cirrí Sur', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Jerónimo', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Juan', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rosario', 'id_canton' => '6', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Palmares', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zaragoza', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Buenos Aires', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Santiago', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Candelaria', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Esquipulas', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Granja', 'id_canton' => '7', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Pedro', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Juan', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Carrillos', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sabana Redonda', 'id_canton' => '8', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Orotina', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Mastate', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Hacienda Vieja', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Coyolar', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Ceiba', 'id_canton' => '9', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Quesada', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Florencia', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Buenavista', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Aguas Zarcas', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Venecia', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Pital', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Fortuna', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tigra', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Palmera', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Venado', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Cutris', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Monterrey', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Pocosol', 'id_canton' => '10', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zarcero', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Laguna', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Tapezco', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Guadalupe', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Palmira', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Zapote', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Brisas', 'id_canton' => '11', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sarchí Norte', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Sarchí Sur', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Toro Amarillo', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Pedro', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Rodríguez', 'id_canton' => '12', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Upala', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Aguas Claras', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San José/Pizote', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Bijagua', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Delicias', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Dos Ríos', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Yolillal', 'id_canton' => '13', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Los Chiles', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Caño Negro', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'El Amparo', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Jorge', 'id_canton' => '14', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'San Rafael', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Buenavista', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
    		['nombre' => 'Cote', 'id_canton' => '15', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
    		]);
    }
}
